/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_wequick_example_small_app_detail_MainActivity */

#ifndef _Included_net_wequick_example_small_app_detail_MainActivity
#define _Included_net_wequick_example_small_app_detail_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_wequick_example_small_app_detail_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_wequick_example_small_app_detail_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
